### ISSUE TITLE
Converting double-enter to paragraph

### ISSUE THREAD

**Issue by firedev** [vmg/redcarpet#448] opened 2015-01-01 15:34 UTC
Hi, 

Is there a way to do parse Markdown with Redcarpet the same way say GitHub does:
```
Long
line

New paragraph
still paragraph
```
Expected HTML:
```
<p>Long line</p>
<p>New paragraph still paragraph</p>
```
Actual HTML:
```
<p>Long line New paragraph still paragraph</p>
```

With `hard_wrap` it adds `<br/>` everywhere, and without it, it ignores double-enter and glues paragraphs together. My users are getting pretty nervous about that. I can't explain them that only triple enter counts as the new paragraph.

Shoulnd't this be the default behaviour?

**Comment by robin850** [comment] 2015-01-12 17:36
Hi @firedev,

Which version of Redcarpet are you using please ? Also are you enabling any extension ? I'm not able to reproduce the problem with Redcarpet 3.2.2 (at least the `\n` are kept inside paragraphs but there are two different paragraphs as expected):

~~~ruby
>> require 'redcarpet';
>>
>> markdown = %(
 | Long
 | line
 | 
 | New paragraph
 | still paragraph
 | );
>>
>> parser = Redcarpet::Markdown.new(Redcarpet::Render::HTML);
>> puts parser.render(markdown)
<p>Long
line</p>

<p>New paragraph
still paragraph</p>
~~~

**Comment by firedev** [comment] 2015-01-12 23:56
I was using `redcarpet (3.2.2)` with the following:

```
Redcarpet::Markdown.new(
      Redcarpet::Render::HTML.new(autolink: true, hard_wrap: true)
).render(text)
```

`hard_wrap` was added after I started to receive complaints. In fact I switched to Kramdown since to see if that is going to change anything. Sorry I didn't investigate the issue thoroughly.

**Comment by robin850** [comment] 2016-06-22 22:38
Okay, closing this one as we don't have more information, thanks for reporting anyway ! :-)

**Closed by robin850** 2016-06-22 22:38 UTC
