### ISSUE TITLE
Test failure with ruby 2.2.2 / Gentoo

### ISSUE THREAD

**Issue by mrueg** [vmg/redcarpet#497] opened 2015-06-23 09:03 UTC
ruby 1.9, ruby 2.0 and ruby 2.1 seems to work, but the tests fail in ruby 2.2. Do you have any idea why this happens?

~~~
>>> Test phase: dev-ruby/redcarpet-3.3.2
 * Running test phase for ruby20 ...
/usr/bin/ruby20 -I"lib:lib:test" -I"/usr/lib64/ruby/gems/2.0.0/gems/rake-10.4.2/lib" "/usr/lib64/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/*_test.rb" 
Run options: 

# Running tests:

Finished tests in 0.259141s, 420.6208 tests/s, 744.7689 assertions/s.
109 tests, 193 assertions, 0 failures, 0 errors, 0 skips

ruby -v: ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-linux]
 * Running test phase for ruby21 ...
/usr/bin/ruby21 -I"lib:lib:test" -I"/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib" "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/*_test.rb" 
Run options: 

# Running tests:

Finished tests in 0.246710s, 441.8150 tests/s, 782.2963 assertions/s.
109 tests, 193 assertions, 0 failures, 0 errors, 0 skips

ruby -v: ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
 * Running test phase for ruby22 ...
/usr/bin/ruby22 -I"lib:lib:test" -I"/usr/lib64/ruby/gems/2.2.0/gems/rake-10.4.2/lib" "/usr/lib64/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/*_test.rb" 
Loaded suite /usr/lib64/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_test_loader
Started
..........................................................................F
===============================================================================
Failure:
  </<mark>/> expected to be =~
  <"<p>A ==simple== fixture file -- with a <a href=\"https://github.com\">link</a>.</p>\n">.
test_enabling_a_parse_option(RedcarpetBinTest)
/var/tmp/portage/dev-ruby/redcarpet-3.3.2/work/ruby22/redcarpet-3.3.2/test/redcarpet_bin_test.rb:74:in `assert_output'
/var/tmp/portage/dev-ruby/redcarpet-3.3.2/work/ruby22/redcarpet-3.3.2/test/redcarpet_bin_test.rb:30:in `test_enabling_a_parse_option'
     27:   def test_enabling_a_parse_option
     28:     run_bin("--parse", "highlight", @fixture_path)
     29: 
  => 30:     assert_output "<mark>"
     31:     refute_output "=="
     32:   end
     33: 
===============================================================================
F
===============================================================================
Failure:
  </\[link\]/> expected to be =~
  <"<p>A ==simple== fixture file -- with a <a href=\"https://github.com\">link</a>.</p>\n">.
test_enabling_a_render_option(RedcarpetBinTest)
/var/tmp/portage/dev-ruby/redcarpet-3.3.2/work/ruby22/redcarpet-3.3.2/test/redcarpet_bin_test.rb:74:in `assert_output'
/var/tmp/portage/dev-ruby/redcarpet-3.3.2/work/ruby22/redcarpet-3.3.2/test/redcarpet_bin_test.rb:37:in `test_enabling_a_render_option'
     34:   def test_enabling_a_render_option
     35:     run_bin("--render", "no-links", @fixture_path)
     36: 
  => 37:     assert_output "[link]"
     38:     refute_output "</a>"
     39:   end
     40: 
===============================================================================
.F
===============================================================================
Failure:
  </<mark>/> expected to be =~
  <"<p>A ==simple== fixture file -- with a <a href=\"https://github.com\">link</a>.</p>\n">.
test_legacy_option_parsing(RedcarpetBinTest)
/var/tmp/portage/dev-ruby/redcarpet-3.3.2/work/ruby22/redcarpet-3.3.2/test/redcarpet_bin_test.rb:74:in `assert_output'
/var/tmp/portage/dev-ruby/redcarpet-3.3.2/work/ruby22/redcarpet-3.3.2/test/redcarpet_bin_test.rb:56:in `test_legacy_option_parsing'
     53:   def test_legacy_option_parsing
     54:     run_bin("--parse-highlight", "--render-no-links", @fixture_path)
     55: 
  => 56:     assert_output "<mark>"
     57:     refute_output "=="
     58: 
     59:     assert_output "[link]"
===============================================================================
...............................

Finished in 0.270107798 seconds.
------
109 tests, 155 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.2477% passed
------
403.54 tests/s, 573.84 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/usr/lib64/ruby/gems/2.2.0/gems/rake-10.4.2/lib" "/usr/lib64/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/*_test.rb" ]

Tasks: TOP => test:unit
(See full trace by running task with --trace)
~~~

**Comment by robin850** [comment] 2015-07-02 11:30
Hi @mrueg,

This seems pretty strange. I'm not able to reproduce this with Ruby 2.2.2 on my computer ; are you using 2.2.2 or a previous version ? I can't find anything that could explain this inside 2.2's changelog.

**Comment by mrueg** [comment] 2015-07-02 11:52
@robin850 I'm using 2.2.2, too. I've tested redcarpet-3.3.0 and 3.3.1, which show the same test failure.

**Comment by robin850** [comment] 2015-07-02 13:20
Hum, and if you try the following:

~~~   
$ echo "A ==simple== fixture file" >> fixture
$ redcarpet --parse highlight fixture
~~~

What is the output please ? I'm wondering whether this is the bin that doesn't work or something wrong inside the test case.

**Comment by mrueg** [comment] 2015-07-02 13:27
ruby22 -S redcarpet --parse highlight fixture
<p>A <mark>simple</mark> fixture file</p>

ruby20 -S redcarpet --parse highlight fixture
<p>A <mark>simple</mark> fixture file</p>

**Comment by mrueg** [comment] 2015-07-02 14:25
Okay, I think I got it.
The issue is caused by https://github.com/vmg/redcarpet/blob/master/bin/redcarpet#L1 and likely a downstream issue. 
In Gentoo one is able to install multiple rubies in parallel, and one changes the symlink of /usr/bin/ruby to the ruby implementation that is desired (ruby 2.0, 2.1, 2.2). 
Tests are run in all variants (we don't change the symlink here, but call the testsuite with each implementation, e.g., /usr/bin/ruby21 directly). This won't work the testsuite calls env to get the path to the ruby binary (which happens here) and caused the issue. I don't know if there's a "proper" upstream fix available, otherwise it works now on Gentoo again.

Thanks for your help!

**Comment by robin850** [comment] 2015-07-03 12:05
Sorry if I'm missing something but I do not understand why this would be a problem ; it is supposed to work with Ruby 1.9.3+ so even if the "wrong" one is picked, it should not output any error.

**Comment by mrueg** [comment] 2015-07-03 14:51
I guess it is caused by the fact, that the test suite is called with e.g. ruby22 but the binary is using another ruby version.

**Comment by robin850** [comment] 2015-07-05 15:29
Yep but this should not be a problem if this version is compatible with Redcarpet. Anyway, I will close this one ; feel free to comment if this comes back later and I will reopen! Thanks! :-)

**Closed by robin850** 2015-07-05 15:29 UTC

**Comment by balasankarc** [comment] 2015-09-03 17:44
@mrueg  How did you solve it, actually? We are facing the same in Debian.

**Comment by mrueg** [comment] 2015-09-03 22:39
@balasankarc https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-ruby/redcarpet/redcarpet-3.3.2.ebuild#n32 
/usr/bin/ruby is actually a symlink to ruby19, ruby20, ruby21 etc. so we'll just fix the shebang line per ruby version
