### ISSUE TITLE
with_toc_data with Japanese

### ISSUE THREAD

**Issue by nasht00** [vmg/redcarpet#538] opened 2016-01-05 11:24 UTC
I have a markdown file in Japanese.

A header might look like:

`## アプリケーション・ストリングの翻訳`

The generated HTML looks like:
`<h2 id=">アプリケーション・ストリングの翻訳</h2>`

As you can see, it's not just that it leaves it empty, it generates invalid HTML (missing closing quote), breaking the entire page.

PS. This is happening inside a Jekyll 3 project

**Comment by eliot-akira** [comment] 2016-01-05 14:17
Funny I was just now experiencing the same issue using Jekyll, and came here to investigate.

~~~
### ヒューマンリーダブル
~~~

...becomes...

~~~
<h3 id=">ヒューマンリーダブル</h3>
~~~

Trial and error showed that even one Japanese character will produce this issue.

**Comment by KitaitiMakoto** [comment] 2016-01-06 05:50
I also encounted the same problem. Minimal code to reproduce the problem is here:

```ruby
# coding: utf-8                                                                                                                                
require 'redcarpet'

puts Redcarpet::VERSION

renderer = Redcarpet::Render::HTML.new(with_toc_data: true)
markdown = Redcarpet::Markdown.new(renderer, {})
puts markdown.render('# 見出し')
```

    $ ruby broken-html.rb
    3.3.4
    <h1 id=">見出し</h1>

As an aside, "見出し" means heading(s).

**Comment by nasht00** [comment] 2016-01-06 07:01
According to last comment, it means it is purely redcarpet and not Jekyll-related.
@robin850 any ideas?

**Comment by IdanAdar** [comment] 2016-01-13 17:32
Any idea if this issue is being tracked by the redcarpet team?

**Comment by scvthedefect** [comment] 2016-01-15 11:31
The heading id is generated by its content. For content do not match `/^\w$/` will cause this bug, id is incomplete and not closed in the right way.

I use heading tags explicitly (`<h1></h1>`) to avoid this but don't feel good.

**Comment by nasht00** [comment] 2016-01-25 06:52
@robin850 or anyone at redcarpet - any news with this?
Can someone review the attached Pull Request see if it's good?
We want to go live soon with our project and this is a problem...

**Comment by akinrt** [comment] 2016-01-29 13:21
@nasht00 hi, this is my solution for now. 
```ruby
class MyRender < Redcarpet::Render::HTML
  def header(text, header_level)
    %Q{<h#{header_level} id="#{text.downcase.gsub(" ", "-")}">#{text}</h#{header_level}>}.html_safe
  end
end
```

**Comment by nasht00** [comment] 2016-02-09 15:21
@akinrt I tried your fix.
It works is most cases, however it breaks if the header contains a link.

For example:

```
### [Setting up Your Development Environment](../setting-up-your-development-environment/)
```

Generates:
```
<h3 id="<a-href="../setting-up-your-development-environment/">setting-up-your-development-environment</a>"><a href="../setting-up-your-development-environment/">Setting up Your Development Environment</a></h3>
```

Which is obviously no good. It used to work before including this fix.

**Comment by robin850** [comment] 2016-02-17 18:37
Hi guys!

We've a bunch of lacks regarding non-ASCII languages, sorry about that and sorry for the late answer here. I will try to have a look as soon as possible. Thanks for reporting !

**Comment by ryush00** [comment] 2016-03-27 14:35
I also have the same issue.

    ### 한글 테스트

=> 

    <h3 id=">한글 테스트</h3>

Any updates? I think 154c318129a40b17c630d186ac7ada7246c01cde cause a problem.

**Comment by IdanAdar** [comment] 2016-03-30 06:32
@robin850 Could this issue please be treated with the appropriate severity, given the many reports?

**Comment by ryush00** [comment] 2016-05-04 16:02
There are some alternatives.

https://www.ruby-toolbox.com/categories/markup_processors

**Comment by ermaker** [comment] 2016-06-22 15:41
Any update?

**Comment by lengerfulluse** [comment] 2016-07-07 08:27
face the same problem with toc extension.
I think the root cause is https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/html.c#L291.  The **_isascii()_** check is not appropriate since it will cause generate empty header id for unicode character(CJK etc).  Two possible solutions.

- use url encode for non-ascii character.
- use alternative **_isutf8()_** or some others check instead.

**Comment by gnujoow** [comment] 2016-11-09 03:23
facing same problem `redcarpet 3.3.4` in korean.

**Closed** 2016-12-25 20:41 UTC
Labels: non-ASCII

**Comment by robin850** [comment] 2016-12-25 21:05
Hi everyone !

#591 should solve this problem ; I'm so sorry for the delay, thank you very much for your patience guys ! This will be part of Redcarpet 3.4.0 that should be released to Rubgems very soon ! Merry Christmas and happy new year ! ❤️ 🎄 🎅 ❄️ ⭐️

**Comment by robin850** [comment] 2016-12-26 13:55
Redcarpet 3.4.0 is available on Rubygems ! Enjoy ! :heart:

**Comment by KitaitiMakoto** [comment] 2016-12-26 13:56
Great!
