### ISSUE TITLE
Heading id cannot be generated properly.

### ISSUE THREAD

**Issue by scvthedefect** [vmg/redcarpet#540] opened 2016-01-15 11:18 UTC
**Issue:**
Id cannot be generated and closed properly while the heading content is in Chinese/Japanese only and causes a disaster for page layout. Example:
```
## 欢迎
```

result:
```
<h2 id=">欢迎</h2>
```
**Reason:**
The id of heading tag is generated by its content, which is assumed to be consist of characters in English, numbers and underscore (RegExp: *\w*). 

issues caused by the same reason:

* [with_toc_data with Japanese #538](https://github.com/vmg/redcarpet/issues/538)
* [Header's tag attribute not close for chinese text #535](https://github.com/vmg/redcarpet/issues/535)

My Solution:
1. Type HTML heading tags manually, such as: `<h1>欢迎</h1>`.
2. Add `&nbsp;` an the beginning: `## &nbsp;欢迎`

Is there any better solution for this issue?

**Comment by namusyaka** [comment] 2016-01-15 11:19
I've tried to fix the problem. See https://github.com/vmg/redcarpet/pull/539

**Comment by scvthedefect** [comment] 2016-01-15 12:34
Thanks. @namusyaka 

May I know your solution for fixing it? I think it might be a better way using an auto-increase index as default id instead of the existing way.

**Comment by nasht00** [comment] 2016-02-08 06:19
Duplicate of #538 ?

**Comment by robin850** [comment] 2016-02-17 18:33
Yep, this looks like a duplicate of #538 ; I'm giving it a close, let's continue the discussion in the latter and in @namusyaka's pull request. Thanks guys !

**Closed by robin850** 2016-02-17 18:33 UTC
