### ISSUE TITLE
More unique footnote reference

### ISSUE THREAD

**Issue by solarsailer** [vmg/redcarpet#469] opened 2015-02-25 00:38 UTC
Hey,

Redcarpet does not differentiate a footnote reference enough:

![screen_shot_2015-02-25_at_01_25_59](https://cloud.githubusercontent.com/assets/478621/6362465/a61fe678-bc8d-11e4-9757-71658f2aeb43.png)

* In the first post, the first footnote has the id "1".
* In the second post, the first footnote has also the id "1". If I click on this one, the page scroll to the first post's first footnote anchor. Indeed, both footnotes have the same "unique" reference (which confuses the browser in my case).

I may have missed a configuration option somewhere (I'm using redcarpet with jekyll). A MD5 of the footnote body instead of a number should prevent this behavior and be enough for most cases I think.

**Comment by mattr-** [comment] 2015-02-25 01:03
is this a single markdown document or a combination of documents?

**Comment by solarsailer** [comment] 2015-02-25 08:50
It's a combination.

**Comment by robin850** [comment] 2015-02-25 18:34
Hi there!

I will close it as a duplicate of #393 ; this would be cool to find a good solution for this issue, this seems more common that what I would expect. Thanks for reporting anyway @solarsailer ! :-)

**Closed by robin850** 2015-02-25 18:34 UTC
