### ISSUE TITLE
What can I do to make HTML_TOC support Simplified Chinese

### ISSUE THREAD

**Issue by zxzllyj** [vmg/redcarpet#565] opened 2016-07-08 02:23 UTC
HTML_TOC currently only supports English, but I need it to support Simplified Chinese, What can I do？

**Comment by zerocool4u2** [comment] 2016-09-12 14:51
i was working with something similar, you could fork the project and modify the c library that works with the headers and add the chinesse characters... that would be painful, i would just add a post processor on ruby that adds the id tag to your headers, 

```ruby
	def md_generator(raw_text)
		renderer = ExtraRenderOptions.new(hard_wrap: true, with_toc_data: true)
		options = {
			fenced_code_blocks: true,
			tables: true,
			space_after_headers: true,
			strikethrough: true,
			footnotes: true,
			autolink: true,
			no_intra_emphasis: true
		}
		post_process(Redcarpet::Markdown.new(renderer, options).render(raw_text)).html_safe
	end
	def post_process(md_text)
		md_text.each_line do |line|
			#TODO: parse the title with maybe nokogiri
			title = "title parsed"
			line.gsub("<h1>", "<h1 id='#{title}>'")
		end
	end
``` 

here some info about get the title http://readysteadycode.com/howto-extract-data-from-html-with-ruby

as a bonus, i'm getting my tocs with this code
```ruby
	# deep is how many levels i want, h1, h2 and h3 would be 3
	def toc(deep)
		current_line = 0;
		prefix = ""
		output = %(## Table of Contents<hr class="sutil-from-left">\r\n\r\n)
		content.each_line do |line|
			forbidden_words = ['Table of contents', 'define', 'pragma']
			next if !line.start_with?("#") || forbidden_words.any? { |w| line =~ /#{w}/ } || line.split.first.count("#") > deep || line.split.first.count("#") != line.split.first.length
			if line.split.first.count("#") == 1
				current_line += 1
				prefix = "#{current_line}."
			else
				prefix = "*"
			end
			title = line.gsub("#", "").strip
			href = title.gsub('"', ' quot ').gsub("'", " 39 ").parameterize
			output+= "   " * (line.split.first.count("#")-1) + "#{prefix} [#{title}](\##{href})\r\n"
		end
		output+= "\r\n"
	end
```

`.gsub('"', ' quot ').gsub("'", " 39 ")` this part is because the c library that makes de tocs ids replace " and ' with quot and 39, hope this helps

**Comment by robin850** [comment] 2016-11-20 17:17
Hi there,

Sorry I haven't given any answer sooner but waiting this bug to be fixed, you can implement a custom render object rather than doing some post-processing like you did @zerocool4u2. There's an example here : https://github.com/vmg/redcarpet/pull/539#issuecomment-245724637.

I'm going to give this a close as a duplicate of #538 hoping that I will be able to fix it soon, thanks anyway guys ! :-)

**Closed by robin850** 2016-11-20 17:17 UTC

**Comment by zxzllyj** [comment] 2016-11-21 02:09
Thank you for your answer, I have rewritten the header method to solve this problem, but not very beautiful
